"""init

Revision ID: 2022_12_17_0007
Revises: 
Create Date: 2022-12-17 00:07:50.793723

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2022_12_17_0007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('larks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('larks')
    # ### end Alembic commands ###
